name: authen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0' # Mở rộng khoảng phiên bản sdk cho tương thích tốt hơn

dependencies:
  flutter:
    sdk: flutter

  # CÁC GÓI PHỤ THUỘC ĐƯỢC ĐẶT Ở ĐÂY, NGANG HÀNG NHAU
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3
  sign_in_button: ^3.2.0 # Gói thông dụng để tạo nút đăng nhập Google/Facebook
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# Phần cấu hình dành riêng cho Flutter bắt đầu ở đây
flutter:

  uses-material-design: true

  # Khai báo assets (hình ảnh, phông chữ, v.v...) ở đây
  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
